version: '3.9'
services:
  postgres:
    image: postgres:latest
    # build:
      # context: .
    environment:
      POSTGRES_DB: dvdrental
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./dvdrental:/dvdrental
      - .db/:/var/lib/postgresql/data
    ports:
      - "5432:5432"